// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: cmd/app/docs/proto/auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_cmd_app_docs_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_app_docs_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_cmd_app_docs_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_cmd_app_docs_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_app_docs_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_cmd_app_docs_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyTokenResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyTokenResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_cmd_app_docs_proto_auth_proto protoreflect.FileDescriptor

const file_cmd_app_docs_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x1dcmd/app/docs/proto/auth.proto\x12\x05proto\"7\n" +
	"\x12VerifyTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"B\n" +
	"\x13VerifyTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role2S\n" +
	"\vAuthService\x12D\n" +
	"\vVerifyToken\x12\x19.proto.VerifyTokenRequest\x1a\x1a.proto.VerifyTokenResponseB\x19Z\x17auth-service/docs/protob\x06proto3"

var (
	file_cmd_app_docs_proto_auth_proto_rawDescOnce sync.Once
	file_cmd_app_docs_proto_auth_proto_rawDescData []byte
)

func file_cmd_app_docs_proto_auth_proto_rawDescGZIP() []byte {
	file_cmd_app_docs_proto_auth_proto_rawDescOnce.Do(func() {
		file_cmd_app_docs_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_app_docs_proto_auth_proto_rawDesc), len(file_cmd_app_docs_proto_auth_proto_rawDesc)))
	})
	return file_cmd_app_docs_proto_auth_proto_rawDescData
}

var file_cmd_app_docs_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_app_docs_proto_auth_proto_goTypes = []any{
	(*VerifyTokenRequest)(nil),  // 0: proto.VerifyTokenRequest
	(*VerifyTokenResponse)(nil), // 1: proto.VerifyTokenResponse
}
var file_cmd_app_docs_proto_auth_proto_depIdxs = []int32{
	0, // 0: proto.AuthService.VerifyToken:input_type -> proto.VerifyTokenRequest
	1, // 1: proto.AuthService.VerifyToken:output_type -> proto.VerifyTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_app_docs_proto_auth_proto_init() }
func file_cmd_app_docs_proto_auth_proto_init() {
	if File_cmd_app_docs_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_app_docs_proto_auth_proto_rawDesc), len(file_cmd_app_docs_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_app_docs_proto_auth_proto_goTypes,
		DependencyIndexes: file_cmd_app_docs_proto_auth_proto_depIdxs,
		MessageInfos:      file_cmd_app_docs_proto_auth_proto_msgTypes,
	}.Build()
	File_cmd_app_docs_proto_auth_proto = out.File
	file_cmd_app_docs_proto_auth_proto_goTypes = nil
	file_cmd_app_docs_proto_auth_proto_depIdxs = nil
}
